### ISSUE TITLE
Kind question about Tantivy

### ISSUE THREAD

**Issue by maximkpa** [zia-ai/humanfirst#1]
Good day!

My name is Maxim, I work at Quickwit as a Digital Marketer. 

We are working on a project of a timeline for Quickwit & Tantivy and we want to feature Humanfirst.ai in it. 

As we know, Humanfirst uses Tantivy, and we wanted to ask when was the first time when you started to use Tantivy in production? (Year is enough, but month is preferred)

Thank you in advance! We are really grateful that you use Tantivy in your project and we hope you love it, just as much as we love your software.

Kind regards,
Maxim Kraynyuchenko
maxim@quickwit.io

**Comment by appaquet** [comment]
Hey Maxim,

We officially started using Tantivy in production in Sep 2021. 

You can ping on me on your Discord if you want to have a chat (same username as on here)

**Comment by maximkpa** [comment]
> Hey Maxim,
> 
> We officially started using Tantivy in production in Sep 2021.
> 
> You can ping on me on your Discord if you want to have a chat (same username as on here)

Thank you so much!! Have a wonderful day! Closing the issue :)
